Remove controller-manager uid and gid settings
CrowdStrike/falcon-operator pull request #198
Opened 2022-02-25 17:03 UTC by redhatrises

- Current uid/gid settings for the controller manager break on more security conscious
  kubernetes distros where uid/gid is generated off of a random uid range that might
  require uid/gid to be > 65000

2022-02-25 17:05 UTC, isimluk requested changes
I always recommend to look at the git history, when something is not making sense on a first sight.

2022-02-25 17:25 UTC, redhatrises commented
I was getting errors deploying the controller due to uid being to small for the uid range... Ironically, now I am not. Closing this for now.

2022-03-08 14:29 UTC, isimluk commented
I have now run into the same issue as well. Ironically, I don't think I did anything to trigger it.

If we merge this, we kinda drop support for OpenShift 4.7 as this piece of config was introduced to support similar yet different error on OpenShift 4.7.

Alternatively, we could drop `runAsNonRoot` hardening and support them all.

2022-03-08 14:30 UTC, isimluk commented
FYI, OpenShift 4.7 is getting close to its EOL: https://access.redhat.com/support/policy/updates/openshift

2022-03-14 09:12 UTC, isimluk approved these changes

2022-03-14 09:13 UTC, merged