Update DS labels for restarting DS when a change is detected
CrowdStrike/falcon-operator pull request #244
Opened 2022-05-24 20:55 UTC by redhatrises

2022-05-25 11:28 UTC, isimluk approved these changes

2022-05-25 11:32 UTC, isimluk commented on pkg/k8s_utils/daemonset.go
> +		LabelSelector: labels.SelectorFromSet(labels.Set{common.FalconInstanceNameKey: ds.Name, common.FalconComponentKey: common.FalconKernelSensor}),
This is not consistent with the values we are setting in. I don't see how this could work?

2022-05-25 11:34 UTC, isimluk requested changes
I think 
```
common.FalconInstanceNameKey: ds.Name
```
needs to be changed to

```
common.FalconInstanceKey: common.FalconKernelSensor
```

2022-06-06 22:32 UTC, redhatrises commented
> common.FalconInstanceKey

Changed it to `common.FalconInstanceKey`

2022-06-07 10:31 UTC, isimluk approved these changes

2022-06-07 10:31 UTC, merged