feat: operator upgrade docs
CrowdStrike/falcon-operator pull request #494
Opened 2024-02-16 20:59 UTC by redhatrises

2024-04-25 02:23 UTC, redhatrises commented on docs/deployment/openshift/README.md
> +## Upgrading
@evanstoner here's the upgrade verbiage for operator capability level 2. I haven't done anything with OLMv1 yet... so not sure if we should do that here as well?

2024-04-26 13:39 UTC, evanstoner requested changes

2024-04-26 15:00 UTC, redhatrises commented on docs/install_guide.md
> +Falcon Operator and Sensor management and upgrades are best handled by using GitOps methodologies and workflows. Multi-Cluster Management tools such as [Red Hat Advanced Cluster Management for Kubern
Fixed

2024-04-26 15:25 UTC, evanstoner approved these changes

2024-04-26 16:30 UTC, merged